org.gradle.jvmargs=-Xmx900m -XX:MaxMetaspaceSize=384m -Dfile.encoding=UTF-8 -XX:+UseSerialGC
org.gradle.parallel=false
org.gradle.daemon=false
org.gradle.workers.max=1
org.gradle.caching=false
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.suppressUnsupportedCompileSdk=35
