package ir.hesabino.app.ui.theme

import androidx.compose.ui.graphics.Color

// ── Brand palette ─────────────────────────────────────────────────────────────
// حسابینو: سبز-فیروزه‌ای مالی روی زمینه‌ی خاکستریِ گرم (سبک شخصی، مدرن، آرام).
val PrimaryLight = Color(0xFF006B54)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF99F2D1)
val OnPrimaryContainerLight = Color(0xFF002115)
val SecondaryLight = Color(0xFF4B635B)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCDE8DE)
val OnSecondaryContainerLight = Color(0xFF07201A)
val TertiaryLight = Color(0xFF3E6375)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFC1E9FE)
val OnTertiaryContainerLight = Color(0xFF001F2A)
val BackgroundLight = Color(0xFFF6FBF8)
val OnBackgroundLight = Color(0xFF171D1A)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF171D1A)
val SurfaceContainerLight = Color(0xFFE8F1ED)
val OnSurfaceVariantLight = Color(0xFF3F4944)
val OutlineLight = Color(0xFFB9C4BE)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)

// Gradient قهرمانی (هدر داشبورد)
val HeroStartLight = Color(0xFF00856B)
val HeroEndLight = Color(0xFF00A67E)

val PrimaryDark = Color(0xFF7CD7B6)
val OnPrimaryDark = Color(0xFF00382A)
val PrimaryContainerDark = Color(0xFF00513E)
val OnPrimaryContainerDark = Color(0xFF99F2D1)
val SecondaryDark = Color(0xFFB1CCC2)
val OnSecondaryDark = Color(0xFF1C352D)
val SecondaryContainerDark = Color(0xFF334B43)
val OnSecondaryContainerDark = Color(0xFFCDE8DE)
val TertiaryDark = Color(0xFFA5CCE0)
val OnTertiaryDark = Color(0xFF073544)
val TertiaryContainerDark = Color(0xFF244C5D)
val OnTertiaryContainerDark = Color(0xFFC1E9FE)
val BackgroundDark = Color(0xFF0F1512)
val OnBackgroundDark = Color(0xFFDEE4E0)
val SurfaceDark = Color(0xFF171D1A)
val OnSurfaceDark = Color(0xFFDEE4E0)
val SurfaceContainerDark = Color(0xFF1B2420)
val OnSurfaceVariantDark = Color(0xFFBFC9C3)
val OutlineDark = Color(0xFF89948D)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)

val HeroStartDark = Color(0xFF006B54)
val HeroEndDark = Color(0xFF00513E)

// رنگ‌های معنایی تراکنش
val Expense = Color(0xFFC0392B)
val ExpenseContainer = Color(0xFFFBE3E0)
val Income = Color(0xFF1F8A5B)
val IncomeContainer = Color(0xFFDDF5E7)
val Transfer = Color(0xFF2F6F8F)
val TransferContainer = Color(0xFFDBEAF2)
val Warning = Color(0xFFC47B12)
val Draft = Color(0xFF6B5B95)
val DraftContainer = Color(0xFFE9E3F5)
